2023-03-03T15:35:19|CRITICAL|root|Unhandled exception:TypeError: setValue(self, int): argument 1 has unexpected type 'float'

2023-03-03T15:35:21|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\GiorgiaT\anaconda3\envs\scopefoundry\lib\site-packages\ScopeFoundry\hardware.py", line 220, in enable_connection
    raise err
  File "C:\Users\GiorgiaT\anaconda3\envs\scopefoundry\lib\site-packages\ScopeFoundry\hardware.py", line 210, in enable_connection
    self.connect()
  File "C:\Users\GiorgiaT\OneDrive - Politecnico di Milano\Desktop\Python\ScopeFoundryProjects\DLP_IO_ScopeFoundry\io_hw.py", line 27, in connect
    self.dlp = Serial(port=self.port.val, baudrate=115200)
  File "C:\Users\GiorgiaT\anaconda3\envs\scopefoundry\lib\site-packages\serial\serialwin32.py", line 33, in __init__
    super(Serial, self).__init__(*args, **kwargs)
  File "C:\Users\GiorgiaT\anaconda3\envs\scopefoundry\lib\site-packages\serial\serialutil.py", line 244, in __init__
    self.open()
  File "C:\Users\GiorgiaT\anaconda3\envs\scopefoundry\lib\site-packages\serial\serialwin32.py", line 64, in open
    raise SerialException("could not open port {!r}: {!r}".format(self.portstr, ctypes.WinError()))
serial.serialutil.SerialException: could not open port 'COM8': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)

2023-03-03T15:35:22|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\GiorgiaT\anaconda3\envs\scopefoundry\lib\site-packages\ScopeFoundry\hardware.py", line 220, in enable_connection
    raise err
  File "C:\Users\GiorgiaT\anaconda3\envs\scopefoundry\lib\site-packages\ScopeFoundry\hardware.py", line 210, in enable_connection
    self.connect()
  File "C:\Users\GiorgiaT\OneDrive - Politecnico di Milano\Desktop\Python\ScopeFoundryProjects\DLP_IO_ScopeFoundry\io_hw.py", line 27, in connect
    self.dlp = Serial(port=self.port.val, baudrate=115200)
  File "C:\Users\GiorgiaT\anaconda3\envs\scopefoundry\lib\site-packages\serial\serialwin32.py", line 33, in __init__
    super(Serial, self).__init__(*args, **kwargs)
  File "C:\Users\GiorgiaT\anaconda3\envs\scopefoundry\lib\site-packages\serial\serialutil.py", line 244, in __init__
    self.open()
  File "C:\Users\GiorgiaT\anaconda3\envs\scopefoundry\lib\site-packages\serial\serialwin32.py", line 64, in open
    raise SerialException("could not open port {!r}: {!r}".format(self.portstr, ctypes.WinError()))
serial.serialutil.SerialException: could not open port 'COM8': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)

