2024-03-20T15:39:31|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\LAB\anaconda3\envs\scopefoundry\lib\site-packages\ScopeFoundry\measurement.py", line 25, in run
    self.measurement._thread_run()
  File "C:\Users\LAB\anaconda3\envs\scopefoundry\lib\site-packages\ScopeFoundry\measurement.py", line 230, in _thread_run
    self.run()
  File "C:\Users\LAB\Scopefoundry_projects\Plant_Macroscope\plant_timelapse_dual_measure.py", line 196, in run
    c.camera.acq_start()
  File "C:\Users\LAB\Scopefoundry_projects\Flir_ScopeFoundry\camera_device.py", line 65, in acq_start
    self.cam.start()
  File "C:\Users\LAB\anaconda3\envs\scopefoundry\lib\site-packages\simple_pyspin\__init__.py", line 180, in start
    self.cam.BeginAcquisition()
  File "C:\Users\LAB\anaconda3\envs\scopefoundry\lib\site-packages\PySpin\PySpin.py", line 34212, in BeginAcquisition
    return _PySpin._SWIG_CamPtr_BeginAcquisition(self)
_PySpin.SpinnakerException: Spinnaker: Camera is already streaming [-1004]

2024-03-20T15:39:41|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\LAB\Scopefoundry_projects\Plant_Macroscope\plant_timelapse_dual_measure.py", line 196, in run
    c.camera.acq_start()
AttributeError: 'FlirHW' object has no attribute 'camera'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\LAB\anaconda3\envs\scopefoundry\lib\site-packages\ScopeFoundry\measurement.py", line 25, in run
    self.measurement._thread_run()
  File "C:\Users\LAB\anaconda3\envs\scopefoundry\lib\site-packages\ScopeFoundry\measurement.py", line 230, in _thread_run
    self.run()
  File "C:\Users\LAB\Scopefoundry_projects\Plant_Macroscope\plant_timelapse_dual_measure.py", line 212, in run
    c.camera.acq_stop()
AttributeError: 'FlirHW' object has no attribute 'camera'

2024-03-20T15:39:50|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\LAB\anaconda3\envs\scopefoundry\lib\site-packages\ScopeFoundry\measurement.py", line 25, in run
    self.measurement._thread_run()
  File "C:\Users\LAB\anaconda3\envs\scopefoundry\lib\site-packages\ScopeFoundry\measurement.py", line 230, in _thread_run
    self.run()
  File "C:\Users\LAB\Scopefoundry_projects\Plant_Macroscope\plant_timelapse_dual_measure.py", line 196, in run
    c.camera.acq_start()
  File "C:\Users\LAB\Scopefoundry_projects\Flir_ScopeFoundry\camera_device.py", line 65, in acq_start
    self.cam.start()
  File "C:\Users\LAB\anaconda3\envs\scopefoundry\lib\site-packages\simple_pyspin\__init__.py", line 180, in start
    self.cam.BeginAcquisition()
  File "C:\Users\LAB\anaconda3\envs\scopefoundry\lib\site-packages\PySpin\PySpin.py", line 34212, in BeginAcquisition
    return _PySpin._SWIG_CamPtr_BeginAcquisition(self)
_PySpin.SpinnakerException: Spinnaker: Camera is already streaming [-1004]

