2024-01-16T15:03:25|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\GiorgiaT\anaconda3\envs\scopefoundry1\lib\site-packages\ScopeFoundry\hardware.py", line 220, in enable_connection
    raise err
  File "C:\Users\GiorgiaT\anaconda3\envs\scopefoundry1\lib\site-packages\ScopeFoundry\hardware.py", line 210, in enable_connection
    self.connect()
  File "C:\Users\GiorgiaT\OneDrive - Politecnico di Milano\Desktop\Python\ScopeFoundryProjects\Flir_ScopeFoundry\camera_hw.py", line 35, in connect
    self.camera = FlirDevice(debug=self.debug_mode.val)
  File "C:\Users\GiorgiaT\OneDrive - Politecnico di Milano\Desktop\Python\ScopeFoundryProjects\Flir_ScopeFoundry\camera_device.py", line 21, in __init__
    self.cam = Camera()
  File "C:\Users\GiorgiaT\anaconda3\envs\scopefoundry1\lib\site-packages\simple_pyspin\__init__.py", line 109, in __init__
    raise CameraError("No cameras detected.")
simple_pyspin.CameraError: No cameras detected.

2024-01-16T15:03:26|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\GiorgiaT\anaconda3\envs\scopefoundry1\lib\site-packages\ScopeFoundry\hardware.py", line 220, in enable_connection
    raise err
  File "C:\Users\GiorgiaT\anaconda3\envs\scopefoundry1\lib\site-packages\ScopeFoundry\hardware.py", line 210, in enable_connection
    self.connect()
  File "C:\Users\GiorgiaT\OneDrive - Politecnico di Milano\Desktop\Python\ScopeFoundryProjects\DLP_IO_ScopeFoundry\io_hw.py", line 27, in connect
    self.dlp = Serial(port=self.port.val, baudrate=115200)
  File "C:\Users\GiorgiaT\anaconda3\envs\scopefoundry1\lib\site-packages\serial\serialwin32.py", line 33, in __init__
    super(Serial, self).__init__(*args, **kwargs)
  File "C:\Users\GiorgiaT\anaconda3\envs\scopefoundry1\lib\site-packages\serial\serialutil.py", line 244, in __init__
    self.open()
  File "C:\Users\GiorgiaT\anaconda3\envs\scopefoundry1\lib\site-packages\serial\serialwin32.py", line 64, in open
    raise SerialException("could not open port {!r}: {!r}".format(self.portstr, ctypes.WinError()))
serial.serialutil.SerialException: could not open port 'COM3': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)

2024-01-16T15:03:27|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\GiorgiaT\anaconda3\envs\scopefoundry1\lib\site-packages\ScopeFoundry\hardware.py", line 220, in enable_connection
    raise err
  File "C:\Users\GiorgiaT\anaconda3\envs\scopefoundry1\lib\site-packages\ScopeFoundry\hardware.py", line 210, in enable_connection
    self.connect()
  File "C:\Users\GiorgiaT\OneDrive - Politecnico di Milano\Desktop\Python\ScopeFoundryProjects\Flir_ScopeFoundry\camera_hw.py", line 35, in connect
    self.camera = FlirDevice(debug=self.debug_mode.val)
  File "C:\Users\GiorgiaT\OneDrive - Politecnico di Milano\Desktop\Python\ScopeFoundryProjects\Flir_ScopeFoundry\camera_device.py", line 21, in __init__
    self.cam = Camera()
  File "C:\Users\GiorgiaT\anaconda3\envs\scopefoundry1\lib\site-packages\simple_pyspin\__init__.py", line 109, in __init__
    raise CameraError("No cameras detected.")
simple_pyspin.CameraError: No cameras detected.

2024-01-16T15:03:28|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\GiorgiaT\anaconda3\envs\scopefoundry1\lib\site-packages\ScopeFoundry\hardware.py", line 220, in enable_connection
    raise err
  File "C:\Users\GiorgiaT\anaconda3\envs\scopefoundry1\lib\site-packages\ScopeFoundry\hardware.py", line 210, in enable_connection
    self.connect()
  File "C:\Users\GiorgiaT\OneDrive - Politecnico di Milano\Desktop\Python\ScopeFoundryProjects\DLP_IO_ScopeFoundry\io_hw.py", line 27, in connect
    self.dlp = Serial(port=self.port.val, baudrate=115200)
  File "C:\Users\GiorgiaT\anaconda3\envs\scopefoundry1\lib\site-packages\serial\serialwin32.py", line 33, in __init__
    super(Serial, self).__init__(*args, **kwargs)
  File "C:\Users\GiorgiaT\anaconda3\envs\scopefoundry1\lib\site-packages\serial\serialutil.py", line 244, in __init__
    self.open()
  File "C:\Users\GiorgiaT\anaconda3\envs\scopefoundry1\lib\site-packages\serial\serialwin32.py", line 64, in open
    raise SerialException("could not open port {!r}: {!r}".format(self.portstr, ctypes.WinError()))
serial.serialutil.SerialException: could not open port 'COM3': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)

