2024-02-16T12:37:20|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:20|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:20|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:21|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:21|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:21|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:21|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:21|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:21|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:21|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:21|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:21|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:22|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:22|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:22|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:22|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:22|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:22|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:22|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:22|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:22|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:23|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:23|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:23|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:23|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:23|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:23|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:23|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:23|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:23|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:24|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:24|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:24|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:24|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:24|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:24|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:24|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:24|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:24|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:25|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:25|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:25|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:25|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:25|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:25|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:25|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:25|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:25|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:25|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:26|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:26|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:26|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:26|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:26|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:26|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:26|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:26|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:26|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:27|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:27|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:27|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:27|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:27|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:27|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:27|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:27|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:27|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:28|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:28|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:28|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:28|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:28|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:28|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:28|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:28|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:28|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:29|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:29|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:29|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:29|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:29|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:29|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:29|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:29|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:30|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:30|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:30|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:30|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:30|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:30|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:30|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:30|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:31|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:31|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:31|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:31|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:31|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:32|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:32|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:32|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:32|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:32|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:33|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:33|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:33|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:33|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:33|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:34|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:34|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:34|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:34|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:35|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:35|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:35|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:35|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:35|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:36|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:36|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:36|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:36|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:37|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:37|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:37|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:37|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:37|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:38|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:38|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:38|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:38|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:39|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:39|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:39|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:39|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:40|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:40|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:40|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:41|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:41|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:41|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:41|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:41|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:42|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:42|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:42|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:42|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:43|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:43|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:43|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:43|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:43|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:44|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:44|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:44|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:45|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:45|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:45|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:46|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:46|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:46|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:47|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:47|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:47|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:48|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:48|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:48|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:49|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:49|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:49|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:50|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:50|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:50|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:51|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T12:37:51|ERROR|PlantTimeLapseMeasure|Plant_TL_measurement Failed to update figure1: 'FlirHW' object has no attribute 'time_lapse_num'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\GiorgiaT\\anaconda3\\envs\\scopefoundry1\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 353, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\GiorgiaT\\OneDrive - Politecnico di Milano\\Desktop\\Python\\ScopeFoundryProjects\\Plant_Macroscope\\plant_timelapse_measure.py", line 91, in update_display\n    length = self.image_gen.time_lapse_num.val\n', "AttributeError: 'FlirHW' object has no attribute 'time_lapse_num'\n"]
2024-02-16T13:49:21|ERROR|camera_app|tried to disconnect DLP_IO: WriteFile failed (PermissionError(13, 'Access is denied.', None, 5))
