2024-01-16T11:08:50|ERROR|camera_app|tried to disconnect DLP_IO: WriteFile failed (PermissionError(13, 'Access is denied.', None, 5))
2024-01-16T11:08:52|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\GiorgiaT\OneDrive - Politecnico di Milano\Desktop\Python\ScopeFoundryProjects\Plant_Macroscope\plant_measure.py", line 151, in run
    self.img = self.image_gen.camera.get_nparray()
  File "C:\Users\GiorgiaT\OneDrive - Politecnico di Milano\Desktop\Python\ScopeFoundryProjects\Flir_ScopeFoundry\camera_device.py", line 68, in get_nparray
    return self.cam.get_array()
  File "C:\Users\GiorgiaT\anaconda3\envs\scopefoundry1\lib\site-packages\simple_pyspin\__init__.py", line 221, in get_array
    img = self.cam.GetNextImage(PySpin.EVENT_TIMEOUT_INFINITE if wait else PySpin.EVENT_TIMEOUT_NONE)
  File "C:\Users\GiorgiaT\anaconda3\envs\scopefoundry1\lib\site-packages\PySpin\PySpin.py", line 34318, in GetNextImage
    return _PySpin._SWIG_CamPtr_GetNextImage(self, *args)
_PySpin.SpinnakerException: Spinnaker: Stream is not started [-1010]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\GiorgiaT\anaconda3\envs\scopefoundry1\lib\site-packages\ScopeFoundry\measurement.py", line 25, in run
    self.measurement._thread_run()
  File "C:\Users\GiorgiaT\anaconda3\envs\scopefoundry1\lib\site-packages\ScopeFoundry\measurement.py", line 230, in _thread_run
    self.run()
  File "C:\Users\GiorgiaT\OneDrive - Politecnico di Milano\Desktop\Python\ScopeFoundryProjects\Plant_Macroscope\plant_measure.py", line 163, in run
    self.image_gen.camera.acq_stop()
AttributeError: 'FlirHW' object has no attribute 'camera'

2024-01-16T11:18:34|ERROR|camera_app|tried to disconnect DLP_IO: WriteFile failed (PermissionError(13, 'Access is denied.', None, 5))
